# Generated by Django 4.2.1 on 2023-12-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogdata_projectdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
